//! Randomness for `wasm32-unknown-unknown` without any JS glue.
//!
//! `minesweeper_core` seeds mine placement and Monte Carlo sampling through
//! `rand::thread_rng`, which asks `getrandom` for entropy. On this target
//! `getrandom` has no backend of its own — its usual one is generated by
//! `wasm-bindgen`, which this crate exists to avoid. So we register a custom
//! backend: JavaScript hands us a single 64-bit seed via `ms_seed`, and we
//! stretch it here with SplitMix64.
//!
//! SplitMix64 is not cryptographic. That is fine: this is a game of minesweeper,
//! and the quality that matters is a well-distributed board, which it delivers.

use std::cell::Cell;

thread_local! {
    /// Fixed non-zero start value, so a page that never calls `ms_seed` still
    /// gets a playable (if reproducible) board instead of an all-zero stream.
    static STATE: Cell<u64> = const { Cell::new(0x2545_F491_4F6C_DD1D) };
}

/// Replace the generator state. Called once from JavaScript at start-up.
pub fn seed(value: u64) {
    // Guard against a zero seed, which SplitMix64 handles fine but which would
    // make two differently-seeded pages agree on their first few boards.
    STATE.with(|state| state.set(value ^ 0x9E37_79B9_7F4A_7C15));
}

/// One SplitMix64 step.
fn next_u64() -> u64 {
    STATE.with(|state| {
        let mut z = state.get().wrapping_add(0x9E37_79B9_7F4A_7C15);
        state.set(z);
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    })
}

/// `getrandom` backend: fill `dest` with successive SplitMix64 outputs.
fn fill_bytes(dest: &mut [u8]) -> Result<(), getrandom::Error> {
    for chunk in dest.chunks_mut(8) {
        let bytes = next_u64().to_le_bytes();
        chunk.copy_from_slice(&bytes[..chunk.len()]);
    }
    Ok(())
}

getrandom::register_custom_getrandom!(fill_bytes);
