#!/usr/bin/env python3
"""Generate docs/standalone.html: index.html with the JS and .wasm inlined.

The result is a single self-contained file that needs no HTTP server at all —
handy for file:// use or for mailing the game to someone. index.html itself
stays a normal three-file page so diffs remain readable.
"""
import base64
import pathlib
import sys

docs = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "docs")

html = (docs / "index.html").read_text(encoding="utf-8")
js = (docs / "minesweeper.js").read_text(encoding="utf-8")
wasm_b64 = base64.b64encode((docs / "minesweeper.wasm").read_bytes()).decode("ascii")

placeholder = '<script src="minesweeper.js"></script>'
if placeholder not in html:
    raise SystemExit("index.html no longer references minesweeper.js; update bundle.py")

inlined = (
    "<!-- Generated by wasm/bundle.py from index.html + minesweeper.js + minesweeper.wasm. "
    "Do not edit by hand. -->\n"
    "<script>var MINESWEEPER_WASM_BASE64 = \"" + wasm_b64 + "\";</script>\n"
    "<script>\n" + js + "\n</script>"
)
banner = (
    "<!-- Self-contained build: everything below is inlined, so this file runs "
    "from a plain file:// URL. Rebuild with wasm/build.sh. -->\n"
)
(docs / "standalone.html").write_text(banner + html.replace(placeholder, inlined), encoding="utf-8")
